######################################################################
# Automatically generated by qmake (3.0) Sat Sep 10 09:05:31 2016
######################################################################

TEMPLATE = app
TARGET = ChkBox
INCLUDEPATH += .
QT += core gui widgets

# Input
HEADERS += Dialog.h 
SOURCES += Dialog.cpp Main.cpp
