######################################################################
# Automatically generated by qmake (3.0) Mon Aug 22 09:12:37 2016
######################################################################

TEMPLATE = app
TARGET = PaintBoard
INCLUDEPATH += .
QT += core
QT += widgets

# Input
HEADERS += mypainterwidget.h
SOURCES += main.cpp mypainterwidget.cpp
