######################################################################
# Automatically generated by qmake (3.0) Tue Mar 7 16:16:22 2017
######################################################################

QT += core widgets network sensors

TEMPLATE = app
TARGET = GyroDemo
INCLUDEPATH += .

# Input
HEADERS += \
    GyroScopeArea.h \
    GyroThread.h \
    mainwindow.h
SOURCES += Main.cpp \
    GyroScopeArea.cpp \
    GyroThread.cpp \
    mainwindow.cpp
