######################################################################
# Automatically generated by qmake (3.0) Sat Feb 18 22:02:43 2017
######################################################################

TEMPLATE = app
TARGET = PaintDemo
INCLUDEPATH += .

QT += core widgets

# Input
HEADERS += MainWindow.h PaintWidget.h
SOURCES += Main.cpp MainWindow.cpp PaintWidget.cpp
