######################################################################
# Automatically generated by qmake (3.0) Thu Jan 19 22:32:30 2017
######################################################################

TEMPLATE = app
TARGET = Cal
INCLUDEPATH += .

QT += core
QT += widgets

# Input
SOURCES += Main.cpp MainWindow.cpp \
    numbutton.cpp
HEADERS += MainWindow.h \
    numbutton.h
