######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 19:27:16 2017
######################################################################

TEMPLATE = app
TARGET = RemoteTouchpad
INCLUDEPATH += .

QT += core
QT += widgets

# Input
HEADERS += MainWindow.h
SOURCES += Main.cpp MainWindow.cpp
