######################################################################
# Automatically generated by qmake (3.0) Mon Sep 12 08:40:35 2016
######################################################################

TEMPLATE = app
TARGET = ComboBox
INCLUDEPATH += .
QT += core gui widgets

# Input
HEADERS += Dialog.h
SOURCES += Dialog.cpp Main.cpp
