######################################################################
# Automatically generated by qmake (3.0) Sat Aug 20 20:53:23 2016
######################################################################

TEMPLATE = app
TARGET = QTerminal
INCLUDEPATH += .
QT += core gui
QT += core widgets

# Input
HEADERS += App.h
SOURCES += App.cpp Main.cpp
