######################################################################
# Automatically generated by qmake (3.0) Sat Aug 20 08:44:25 2016
######################################################################

TEMPLATE = app
TARGET = SignalSlot
INCLUDEPATH += .
QT += core gui

greaterThan( QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += MainWindow.h
SOURCES += Main.cpp MainWindow.cpp
